Constant::ScaleCategory.create!([
  { id: 1, name: '基本的なスケール' },
  { id: 2, name: 'モードスケール（メジャー/ナチュラルマイナー）' },
  { id: 3, name: 'モードスケール（ハーモニックマイナー）' },
  { id: 4, name: 'モードスケール（メロディックマイナー）' },
  { id: 5, name: 'ペンタトニック/ブルーススケール' },
  { id: 6, name: 'シンメトリカルスケール' },
  { id: 7, name: 'その他のスケール' },
])

Constant::Scale.create!([
  # 基本的なスケール
  { id: 1, scale_category_id: 1, path: 'major', name: 'メジャースケール',
    description: '主音[0]から全音-全音-半音-全音-全音-全音-半音の間隔で並ぶスケール。' },
  { id: 2, scale_category_id: 1, path: 'natural-minor', name: 'ナチュラルマイナースケール',
    description: '主音[0]から全音-半音-全音-全音-半音-全音-全音の間隔で並ぶスケール。' },
  { id: 3, scale_category_id: 1, path: 'harmonic-minor', name: 'ハーモニックマイナースケール',
    description: '{interval:0,scale_id:2}の第７音を半音上げて作られるスケール。' },
  { id: 4, scale_category_id: 1, path: 'melodic-minor', name: 'メロディックマイナースケール',
    description: '{interval:0,scale_id:3}の第６音を半音上げて作られるスケール。' },
  # モードスケール（メジャー/ナチュラルマイナー）
  { id: 5, scale_category_id: 2, path: 'ionian', name: 'アイオニアンスケール',
    description: '{interval:0,scale_id:1}の主音、または{interval:5,scale_id:2}の第３音から始まるモードスケール。' },
  { id: 6, scale_category_id: 2, path: 'dorian', name: 'ドリアンスケール',
    description: '{interval:6,scale_id:1}の第２音、または{interval:4,scale_id:2}の第４音から始まるモードスケール。' },
  { id: 7, scale_category_id: 2, path: 'phrygian', name: 'フリジアンスケール',
    description: '{interval:5,scale_id:1}の第３音、または{interval:3,scale_id:2}の第５音から始まるモードスケール。' },
  { id: 8, scale_category_id: 2, path: 'lydian', name: 'リディアンスケール',
    description: '{interval:4,scale_id:1}の第４音、または{interval:2,scale_id:2}の第６音から始まるモードスケール。' },
  { id: 9, scale_category_id: 2, path: 'mixolydian', name: 'ミクソリディアンスケール',
    description: '{interval:3,scale_id:1}の第５音、または{interval:1,scale_id:2}の第７音から始まるモードスケール。' },
  { id: 10, scale_category_id: 2, path: 'aeolian', name: 'エオリアンスケール',
    description: '{interval:2,scale_id:1}の第６音、または{interval:0,scale_id:2}の主音から始まるモードスケール。' },
  { id: 11, scale_category_id: 2, path: 'locrian', name: 'ロクリアンスケール',
    description: '{interval:1,scale_id:1}の第７音、または{interval:6,scale_id:2}の第２音から始まるモードスケール。' },
  # モードスケール（ハーモニックマイナー）
  { id: 12, scale_category_id: 3, path: 'locrian-sharp6', name: 'ロクリアン#６スケール',
    description: '{interval:6,scale_id:3}の第２音から始まるモードスケール。' },
  { id: 13, scale_category_id: 3, path: 'ionian-sharp5', name: 'アイオニアン#５スケール',
    description: '{interval:5,scale_id:3}の第３音から始まるモードスケール。' },
  { id: 14, scale_category_id: 3, path: 'dorian-sharp4', name: 'ドリアン#４スケール',
    description: '{interval:4,scale_id:3}の第４音から始まるモードスケール。' },
  { id: 15, scale_category_id: 3, path: 'phrygian-dominant', name: 'フリジアンドミナントスケール',
    description: '{interval:3,scale_id:3}の第５音から始まるモードスケール。' },
  { id: 16, scale_category_id: 3, path: 'lydian-sharp2', name: 'リディアン#２スケール',
    description: '{interval:2,scale_id:3}の第６音から始まるモードスケール。' },
  { id: 17, scale_category_id: 3, path: 'super-locrian-flat7', name: 'スーパーロクリアンb７スケール',
    description: '{interval:1,scale_id:3}の第７音から始まるモードスケール。' },
  # モードスケール（メロディックマイナー）
  { id: 18, scale_category_id: 4, path: 'phrygian-sharp6', name: 'フリジアン#６スケール',
    description: '{interval:6,scale_id:4}の第２音から始まるモードスケール。' },
  { id: 19, scale_category_id: 4, path: 'lydian-sharp5', name: 'リディアン#５スケール',
    description: '{interval:5,scale_id:4}の第３音から始まるモードスケール。' },
  { id: 20, scale_category_id: 4, path: 'mixolydian-sharp4', name: 'ミクソリディアン#４スケール',
    description: '{interval:4,scale_id:4}の第４音から始まるモードスケール。' },
  { id: 21, scale_category_id: 4, path: 'aeolian-dominant', name: 'エオリアンドミナントスケール',
    description: '{interval:3,scale_id:4}の第５音から始まるモードスケール。' },
  { id: 22, scale_category_id: 4, path: 'locrian-sharp2', name: 'ロクリアン#２スケール',
    description: '{interval:2,scale_id:4}の第６音から始まるモードスケール。' },
  { id: 23, scale_category_id: 4, path: 'super-locrian', name: 'スーパーロクリアンスケール',
    description: '{interval:1,scale_id:4}の第７音から始まるモードスケール。' },
  # ペンタトニック/ブルーススケール
  { id: 24, scale_category_id: 5, path: 'major-pentatonic', name: 'メジャーペンタトニックスケール',
    description: '{interval:0,scale_id:1}の第４音，第７音を省略したスケール。' },
  { id: 25, scale_category_id: 5, path: 'minor-pentatonic', name: 'マイナーペンタトニックスケール',
    description: '{interval:0,scale_id:2}の第２音，第６音を省略したスケール。' },
  { id: 26, scale_category_id: 5, path: 'major-blues', name: 'メジャーブルーススケール',
    description: '{interval:0,scale_id:24}に短３度の音を加えたスケール。' },
  { id: 27, scale_category_id: 5, path: 'minor-blues', name: 'マイナーブルーススケール',
    description: '{interval:0,scale_id:25}に減５度の音を加えたスケール。' },
  # シンメトリカルスケール
  { id: 28, scale_category_id: 6, path: 'wholetone', name: 'ホールトーンスケール',
    description: '主音[0]から全音の間隔で均等に並ぶスケール。' },
  { id: 29, scale_category_id: 6, path: 'diminished', name: 'ディミニッシュスケール',
    description: '主音[0]から全音-半音-全音-半音-全音-半音-全音の間隔で並ぶスケール。' },
  { id: 30, scale_category_id: 6, path: 'dominant-diminished', name: 'ドミナントディミニッシュスケール',
    description: '主音[0]から半音-全音-半音-全音-半音-全音-半音の間隔で並ぶスケール。' },
  # その他のスケール
  { id: 31, scale_category_id: 7, path: 'altered', name: 'オルタードスケール',
    description: '主音[0]から半音-全音-半音-全音-全音-全音-全音の間隔で並ぶ、b9, #9, #11, b13が含まれたスケール。' },
  { id: 32, scale_category_id: 7, path: 'bebop-dominant', name: 'ビバップドミナントスケール',
    description: '{interval:0,scale_id:9}に長７度の音を加えたスケール。' }
])

Constant::Accidental.create!([
  { id: 1, name: '' },
  { id: 2, name: 'sharp' },
  { id: 3, name: 'flat' }
])

Constant::Interval.create!([
  { id: 1, name: 'perfect1st' },
  { id: 2, name: 'minor2nd' },
  { id: 3, name: 'major2nd' },
  { id: 4, name: 'minor3rd' },
  { id: 5, name: 'major3rd' },
  { id: 6, name: 'diminished4th' },
  { id: 7, name: 'perfect4th' },
  { id: 8, name: 'augmented4th' },
  { id: 9, name: 'diminished5th' },
  { id: 10, name: 'perfect5th' },
  { id: 11, name: 'augmented5th' },
  { id: 12, name: 'minor6th' },
  { id: 13, name: 'major6th' },
  { id: 14, name: 'diminished7th' },
  { id: 15, name: 'minor7th' },
  { id: 16, name: 'major7th' },
  { id: 17, name: 'flat9th' },
  { id: 18, name: '9th' },
  { id: 19, name: 'sharp9th' },
  { id: 20, name: '11th' },
  { id: 21, name: 'sharp11th' },
  { id: 22, name: 'flat13th' },
  { id: 23, name: '13th' }
])

Constant::ToneType.create!([
  { id: 1, name: 'コードトーン' },
  { id: 2, name: 'テンションノート' },
  { id: 3, name: 'アボイドノート' },
  { id: 4, name: 'ブルーノート' },
  { id: 5, name: 'パッシングノート' }
])

Constant::ScaleTone.create!([
  # メジャースケール
  { id: 1, scale_id: 1, semitone_cnt: 0, accidental_id: 1, interval_id: 1, tone_type_id: 1 },
  { id: 2, scale_id: 1, semitone_cnt: 2, accidental_id: 1, interval_id: 18, tone_type_id: 2 },
  { id: 3, scale_id: 1, semitone_cnt: 4, accidental_id: 1, interval_id: 5, tone_type_id: 1 },
  { id: 4, scale_id: 1, semitone_cnt: 5, accidental_id: 1, interval_id: 20, tone_type_id: 3 },
  { id: 5, scale_id: 1, semitone_cnt: 7, accidental_id: 1, interval_id: 10, tone_type_id: 1 },
  { id: 6, scale_id: 1, semitone_cnt: 9, accidental_id: 1, interval_id: 13, tone_type_id: 1 },
  { id: 7, scale_id: 1, semitone_cnt: 11, accidental_id: 1, interval_id: 16, tone_type_id: 1 },
  # ナチュラルマイナースケール
  { id: 8, scale_id: 2, semitone_cnt: 0, accidental_id: 1, interval_id: 1, tone_type_id: 1 },
  { id: 9, scale_id: 2, semitone_cnt: 2, accidental_id: 1, interval_id: 18, tone_type_id: 2 },
  { id: 10, scale_id: 2, semitone_cnt: 3, accidental_id: 1, interval_id: 4, tone_type_id: 1 },
  { id: 11, scale_id: 2, semitone_cnt: 5, accidental_id: 1, interval_id: 20, tone_type_id: 2 },
  { id: 12, scale_id: 2, semitone_cnt: 7, accidental_id: 1, interval_id: 10, tone_type_id: 1 },
  { id: 13, scale_id: 2, semitone_cnt: 8, accidental_id: 1, interval_id: 22, tone_type_id: 3 },
  { id: 14, scale_id: 2, semitone_cnt: 10, accidental_id: 1, interval_id: 15, tone_type_id: 1 },
  # ハーモニックマイナースケール
  { id: 15, scale_id: 3, semitone_cnt: 0, accidental_id: 1, interval_id: 1, tone_type_id: 1 },
  { id: 16, scale_id: 3, semitone_cnt: 2, accidental_id: 1, interval_id: 18, tone_type_id: 2 },
  { id: 17, scale_id: 3, semitone_cnt: 3, accidental_id: 1, interval_id: 4, tone_type_id: 1 },
  { id: 18, scale_id: 3, semitone_cnt: 5, accidental_id: 1, interval_id: 20, tone_type_id: 2 },
  { id: 19, scale_id: 3, semitone_cnt: 7, accidental_id: 1, interval_id: 10, tone_type_id: 1 },
  { id: 20, scale_id: 3, semitone_cnt: 8, accidental_id: 1, interval_id: 22, tone_type_id: 3 },
  { id: 21, scale_id: 3, semitone_cnt: 10, accidental_id: 2, interval_id: 16, tone_type_id: 1 },
  # メロディックマイナースケール
  { id: 22, scale_id: 4, semitone_cnt: 0, accidental_id: 1, interval_id: 1, tone_type_id: 1 },
  { id: 23, scale_id: 4, semitone_cnt: 2, accidental_id: 1, interval_id: 18, tone_type_id: 2 },
  { id: 24, scale_id: 4, semitone_cnt: 3, accidental_id: 1, interval_id: 4, tone_type_id: 1 },
  { id: 25, scale_id: 4, semitone_cnt: 5, accidental_id: 1, interval_id: 20, tone_type_id: 2 },
  { id: 26, scale_id: 4, semitone_cnt: 7, accidental_id: 1, interval_id: 10, tone_type_id: 1 },
  { id: 27, scale_id: 4, semitone_cnt: 8, accidental_id: 2, interval_id: 13, tone_type_id: 1 },
  { id: 28, scale_id: 4, semitone_cnt: 10, accidental_id: 2, interval_id: 16, tone_type_id: 1 },
  # アイオニアンスケール
  { id: 29, scale_id: 5, semitone_cnt: 0, accidental_id: 1, interval_id: 1, tone_type_id: 1 },
  { id: 30, scale_id: 5, semitone_cnt: 2, accidental_id: 1, interval_id: 18, tone_type_id: 2 },
  { id: 31, scale_id: 5, semitone_cnt: 4, accidental_id: 1, interval_id: 5, tone_type_id: 1 },
  { id: 32, scale_id: 5, semitone_cnt: 5, accidental_id: 1, interval_id: 20, tone_type_id: 3 },
  { id: 33, scale_id: 5, semitone_cnt: 7, accidental_id: 1, interval_id: 10, tone_type_id: 1 },
  { id: 34, scale_id: 5, semitone_cnt: 9, accidental_id: 1, interval_id: 13, tone_type_id: 1 },
  { id: 35, scale_id: 5, semitone_cnt: 11, accidental_id: 1, interval_id: 16, tone_type_id: 1 },
  # ドリアンスケール
  { id: 36, scale_id: 6, semitone_cnt: 0, accidental_id: 1, interval_id: 1, tone_type_id: 1 },
  { id: 37, scale_id: 6, semitone_cnt: 2, accidental_id: 1, interval_id: 18, tone_type_id: 2 },
  { id: 38, scale_id: 6, semitone_cnt: 3, accidental_id: 1, interval_id: 4, tone_type_id: 1 },
  { id: 39, scale_id: 6, semitone_cnt: 5, accidental_id: 1, interval_id: 20, tone_type_id: 2 },
  { id: 40, scale_id: 6, semitone_cnt: 7, accidental_id: 1, interval_id: 10, tone_type_id: 1 },
  { id: 41, scale_id: 6, semitone_cnt: 9, accidental_id: 1, interval_id: 23, tone_type_id: 3 },
  { id: 42, scale_id: 6, semitone_cnt: 10, accidental_id: 1, interval_id: 15, tone_type_id: 1 },
  # フリジアンスケール
  { id: 43, scale_id: 7, semitone_cnt: 0, accidental_id: 1, interval_id: 1, tone_type_id: 1 },
  { id: 44, scale_id: 7, semitone_cnt: 1, accidental_id: 1, interval_id: 17, tone_type_id: 3 },
  { id: 45, scale_id: 7, semitone_cnt: 3, accidental_id: 1, interval_id: 4, tone_type_id: 1 },
  { id: 46, scale_id: 7, semitone_cnt: 5, accidental_id: 1, interval_id: 20, tone_type_id: 2 },
  { id: 47, scale_id: 7, semitone_cnt: 7, accidental_id: 1, interval_id: 10, tone_type_id: 1 },
  { id: 48, scale_id: 7, semitone_cnt: 8, accidental_id: 1, interval_id: 22, tone_type_id: 3 },
  { id: 49, scale_id: 7, semitone_cnt: 10, accidental_id: 1, interval_id: 15, tone_type_id: 1 },
  # リディアンスケール
  { id: 50, scale_id: 8, semitone_cnt: 0, accidental_id: 1, interval_id: 1, tone_type_id: 1 },
  { id: 51, scale_id: 8, semitone_cnt: 2, accidental_id: 1, interval_id: 18, tone_type_id: 2 },
  { id: 52, scale_id: 8, semitone_cnt: 4, accidental_id: 1, interval_id: 5, tone_type_id: 1 },
  { id: 53, scale_id: 8, semitone_cnt: 6, accidental_id: 1, interval_id: 21, tone_type_id: 2 },
  { id: 54, scale_id: 8, semitone_cnt: 7, accidental_id: 1, interval_id: 10, tone_type_id: 1 },
  { id: 55, scale_id: 8, semitone_cnt: 9, accidental_id: 1, interval_id: 13, tone_type_id: 1 },
  { id: 56, scale_id: 8, semitone_cnt: 11, accidental_id: 1, interval_id: 16, tone_type_id: 1 },
  # ミクソリディアンスケール
  { id: 57, scale_id: 9, semitone_cnt: 0, accidental_id: 1, interval_id: 1, tone_type_id: 1 },
  { id: 58, scale_id: 9, semitone_cnt: 2, accidental_id: 1, interval_id: 18, tone_type_id: 2 },
  { id: 59, scale_id: 9, semitone_cnt: 4, accidental_id: 1, interval_id: 5, tone_type_id: 1 },
  { id: 60, scale_id: 9, semitone_cnt: 5, accidental_id: 1, interval_id: 20, tone_type_id: 3 },
  { id: 61, scale_id: 9, semitone_cnt: 7, accidental_id: 1, interval_id: 10, tone_type_id: 1 },
  { id: 62, scale_id: 9, semitone_cnt: 9, accidental_id: 1, interval_id: 23, tone_type_id: 2 },
  { id: 63, scale_id: 9, semitone_cnt: 10, accidental_id: 1, interval_id: 15, tone_type_id: 1 },
  # エオリアンスケール
  { id: 64, scale_id: 10, semitone_cnt: 0, accidental_id: 1, interval_id: 1, tone_type_id: 1 },
  { id: 65, scale_id: 10, semitone_cnt: 2, accidental_id: 1, interval_id: 18, tone_type_id: 2 },
  { id: 66, scale_id: 10, semitone_cnt: 3, accidental_id: 1, interval_id: 4, tone_type_id: 1 },
  { id: 67, scale_id: 10, semitone_cnt: 5, accidental_id: 1, interval_id: 20, tone_type_id: 2 },
  { id: 68, scale_id: 10, semitone_cnt: 7, accidental_id: 1, interval_id: 10, tone_type_id: 1 },
  { id: 69, scale_id: 10, semitone_cnt: 8, accidental_id: 1, interval_id: 22, tone_type_id: 3 },
  { id: 70, scale_id: 10, semitone_cnt: 10, accidental_id: 1, interval_id: 15, tone_type_id: 1 },
  # ロクリアンスケール
  { id: 71, scale_id: 11, semitone_cnt: 0, accidental_id: 1, interval_id: 1, tone_type_id: 1 },
  { id: 72, scale_id: 11, semitone_cnt: 1, accidental_id: 1, interval_id: 17, tone_type_id: 3 },
  { id: 73, scale_id: 11, semitone_cnt: 3, accidental_id: 1, interval_id: 4, tone_type_id: 1 },
  { id: 74, scale_id: 11, semitone_cnt: 5, accidental_id: 1, interval_id: 20, tone_type_id: 2 },
  { id: 75, scale_id: 11, semitone_cnt: 6, accidental_id: 1, interval_id: 9, tone_type_id: 1 },
  { id: 76, scale_id: 11, semitone_cnt: 8, accidental_id: 1, interval_id: 22, tone_type_id: 2 },
  { id: 77, scale_id: 11, semitone_cnt: 10, accidental_id: 1, interval_id: 15, tone_type_id: 1 },
  # ロクリアン#6スケール
  { id: 78, scale_id: 12, semitone_cnt: 0, accidental_id: 1, interval_id: 1, tone_type_id: 1 },
  { id: 79, scale_id: 12, semitone_cnt: 1, accidental_id: 1, interval_id: 17, tone_type_id: 3 },
  { id: 80, scale_id: 12, semitone_cnt: 3, accidental_id: 1, interval_id: 4, tone_type_id: 1 },
  { id: 81, scale_id: 12, semitone_cnt: 5, accidental_id: 1, interval_id: 20, tone_type_id: 2 },
  { id: 82, scale_id: 12, semitone_cnt: 6, accidental_id: 1, interval_id: 9, tone_type_id: 1 },
  { id: 83, scale_id: 12, semitone_cnt: 8, accidental_id: 2, interval_id: 23, tone_type_id: 2 },
  { id: 84, scale_id: 12, semitone_cnt: 10, accidental_id: 1, interval_id: 15, tone_type_id: 1 },
  # アイオニアン#5スケール
  { id: 85, scale_id: 13, semitone_cnt: 0, accidental_id: 1, interval_id: 1, tone_type_id: 1 },
  { id: 86, scale_id: 13, semitone_cnt: 2, accidental_id: 1, interval_id: 18, tone_type_id: 2 },
  { id: 87, scale_id: 13, semitone_cnt: 4, accidental_id: 1, interval_id: 5, tone_type_id: 1 },
  { id: 88, scale_id: 13, semitone_cnt: 5, accidental_id: 1, interval_id: 20, tone_type_id: 3 },
  { id: 89, scale_id: 13, semitone_cnt: 7, accidental_id: 2, interval_id: 11, tone_type_id: 1 },
  { id: 90, scale_id: 13, semitone_cnt: 9, accidental_id: 1, interval_id: 13, tone_type_id: 1 },
  { id: 91, scale_id: 13, semitone_cnt: 11, accidental_id: 1, interval_id: 16, tone_type_id: 1 },
  # ドリアン#4スケール
  { id: 92, scale_id: 14, semitone_cnt: 0, accidental_id: 1, interval_id: 1, tone_type_id: 1 },
  { id: 93, scale_id: 14, semitone_cnt: 2, accidental_id: 1, interval_id: 18, tone_type_id: 2 },
  { id: 94, scale_id: 14, semitone_cnt: 3, accidental_id: 1, interval_id: 4, tone_type_id: 1 },
  { id: 95, scale_id: 14, semitone_cnt: 5, accidental_id: 2, interval_id: 21, tone_type_id: 2 },
  { id: 96, scale_id: 14, semitone_cnt: 7, accidental_id: 1, interval_id: 10, tone_type_id: 1 },
  { id: 97, scale_id: 14, semitone_cnt: 9, accidental_id: 1, interval_id: 23, tone_type_id: 1 },
  { id: 98, scale_id: 14, semitone_cnt: 10, accidental_id: 1, interval_id: 15, tone_type_id: 1 },
  # フリジアンドミナントスケール
  { id: 99, scale_id: 15, semitone_cnt: 0, accidental_id: 1, interval_id: 1, tone_type_id: 1 },
  { id: 100, scale_id: 15, semitone_cnt: 1, accidental_id: 1, interval_id: 17, tone_type_id: 2 },
  { id: 101, scale_id: 15, semitone_cnt: 3, accidental_id: 2, interval_id: 5, tone_type_id: 1 },
  { id: 102, scale_id: 15, semitone_cnt: 5, accidental_id: 1, interval_id: 20, tone_type_id: 3 },
  { id: 103, scale_id: 15, semitone_cnt: 7, accidental_id: 1, interval_id: 10, tone_type_id: 1 },
  { id: 104, scale_id: 15, semitone_cnt: 8, accidental_id: 1, interval_id: 22, tone_type_id: 2 },
  { id: 105, scale_id: 15, semitone_cnt: 10, accidental_id: 1, interval_id: 15, tone_type_id: 1 },
  # リディアン#2スケール
  { id: 106, scale_id: 16, semitone_cnt: 0, accidental_id: 1, interval_id: 1, tone_type_id: 1 },
  { id: 107, scale_id: 16, semitone_cnt: 2, accidental_id: 2, interval_id: 19, tone_type_id: 2 },
  { id: 108, scale_id: 16, semitone_cnt: 4, accidental_id: 1, interval_id: 5, tone_type_id: 1 },
  { id: 109, scale_id: 16, semitone_cnt: 6, accidental_id: 1, interval_id: 21, tone_type_id: 2 },
  { id: 110, scale_id: 16, semitone_cnt: 7, accidental_id: 1, interval_id: 10, tone_type_id: 1 },
  { id: 111, scale_id: 16, semitone_cnt: 9, accidental_id: 1, interval_id: 13, tone_type_id: 1 },
  { id: 112, scale_id: 16, semitone_cnt: 11, accidental_id: 1, interval_id: 16, tone_type_id: 1 },
  # スーパーロクリアンb7スケール
  { id: 113, scale_id: 17, semitone_cnt: 0, accidental_id: 1, interval_id: 1, tone_type_id: 1 },
  { id: 114, scale_id: 17, semitone_cnt: 1, accidental_id: 1, interval_id: 17, tone_type_id: 3 },
  { id: 115, scale_id: 17, semitone_cnt: 3, accidental_id: 1, interval_id: 4, tone_type_id: 1 },
  { id: 116, scale_id: 17, semitone_cnt: 4, accidental_id: 1, interval_id: 6, tone_type_id: 3 },
  { id: 117, scale_id: 17, semitone_cnt: 6, accidental_id: 1, interval_id: 9, tone_type_id: 1 },
  { id: 118, scale_id: 17, semitone_cnt: 8, accidental_id: 1, interval_id: 22, tone_type_id: 2 },
  { id: 119, scale_id: 17, semitone_cnt: 9, accidental_id: 1, interval_id: 14, tone_type_id: 1 },
  # フリジアン#6スケール
  { id: 120, scale_id: 18, semitone_cnt: 0, accidental_id: 1, interval_id: 1, tone_type_id: 1 },
  { id: 121, scale_id: 18, semitone_cnt: 1, accidental_id: 1, interval_id: 17, tone_type_id: 3 },
  { id: 122, scale_id: 18, semitone_cnt: 3, accidental_id: 1, interval_id: 4, tone_type_id: 1 },
  { id: 123, scale_id: 18, semitone_cnt: 5, accidental_id: 1, interval_id: 20, tone_type_id: 2 },
  { id: 124, scale_id: 18, semitone_cnt: 6, accidental_id: 2, interval_id: 10, tone_type_id: 1 },
  { id: 125, scale_id: 18, semitone_cnt: 8, accidental_id: 2, interval_id: 23, tone_type_id: 2 },
  { id: 126, scale_id: 18, semitone_cnt: 10, accidental_id: 1, interval_id: 15, tone_type_id: 1 },
  # リディアン#5スケール
  { id: 127, scale_id: 19, semitone_cnt: 0, accidental_id: 1, interval_id: 1, tone_type_id: 1 },
  { id: 128, scale_id: 19, semitone_cnt: 2, accidental_id: 1, interval_id: 18, tone_type_id: 2 },
  { id: 129, scale_id: 19, semitone_cnt: 4, accidental_id: 1, interval_id: 5, tone_type_id: 1 },
  { id: 130, scale_id: 19, semitone_cnt: 5, accidental_id: 2, interval_id: 21, tone_type_id: 2 },
  { id: 131, scale_id: 19, semitone_cnt: 7, accidental_id: 2, interval_id: 11, tone_type_id: 1 },
  { id: 132, scale_id: 19, semitone_cnt: 9, accidental_id: 1, interval_id: 13, tone_type_id: 1 },
  { id: 133, scale_id: 19, semitone_cnt: 11, accidental_id: 1, interval_id: 16, tone_type_id: 1 },
  # ミクソリディアン#4スケール
  { id: 134, scale_id: 20, semitone_cnt: 0, accidental_id: 1, interval_id: 1, tone_type_id: 1 },
  { id: 135, scale_id: 20, semitone_cnt: 2, accidental_id: 1, interval_id: 18, tone_type_id: 2 },
  { id: 136, scale_id: 20, semitone_cnt: 3, accidental_id: 2, interval_id: 5, tone_type_id: 1 },
  { id: 137, scale_id: 20, semitone_cnt: 5, accidental_id: 2, interval_id: 21, tone_type_id: 2 },
  { id: 138, scale_id: 20, semitone_cnt: 7, accidental_id: 1, interval_id: 10, tone_type_id: 1 },
  { id: 139, scale_id: 20, semitone_cnt: 9, accidental_id: 1, interval_id: 23, tone_type_id: 2 },
  { id: 140, scale_id: 20, semitone_cnt: 10, accidental_id: 1, interval_id: 15, tone_type_id: 1 },
  # エオリアンドミナントスケール
  { id: 141, scale_id: 21, semitone_cnt: 0, accidental_id: 1, interval_id: 1, tone_type_id: 1 },
  { id: 142, scale_id: 21, semitone_cnt: 1, accidental_id: 2, interval_id: 18, tone_type_id: 2 },
  { id: 143, scale_id: 21, semitone_cnt: 3, accidental_id: 2, interval_id: 5, tone_type_id: 1 },
  { id: 144, scale_id: 21, semitone_cnt: 5, accidental_id: 1, interval_id: 20, tone_type_id: 3 },
  { id: 145, scale_id: 21, semitone_cnt: 7, accidental_id: 1, interval_id: 10, tone_type_id: 1 },
  { id: 146, scale_id: 21, semitone_cnt: 8, accidental_id: 1, interval_id: 22, tone_type_id: 2 },
  { id: 147, scale_id: 21, semitone_cnt: 10, accidental_id: 1, interval_id: 15, tone_type_id: 1 },
  # ロクリアン#2スケール
  { id: 148, scale_id: 22, semitone_cnt: 0, accidental_id: 1, interval_id: 1, tone_type_id: 1 },
  { id: 149, scale_id: 22, semitone_cnt: 1, accidental_id: 2, interval_id: 18, tone_type_id: 2 },
  { id: 150, scale_id: 22, semitone_cnt: 3, accidental_id: 1, interval_id: 4, tone_type_id: 1 },
  { id: 151, scale_id: 22, semitone_cnt: 5, accidental_id: 1, interval_id: 20, tone_type_id: 2 },
  { id: 152, scale_id: 22, semitone_cnt: 6, accidental_id: 1, interval_id: 9, tone_type_id: 1 },
  { id: 153, scale_id: 22, semitone_cnt: 8, accidental_id: 1, interval_id: 22, tone_type_id: 2 },
  { id: 154, scale_id: 22, semitone_cnt: 10, accidental_id: 1, interval_id: 15, tone_type_id: 1 },
  # スーパーロクリアンスケール
  { id: 155, scale_id: 23, semitone_cnt: 0, accidental_id: 1, interval_id: 1, tone_type_id: 1 },
  { id: 156, scale_id: 23, semitone_cnt: 1, accidental_id: 1, interval_id: 17, tone_type_id: 3 },
  { id: 157, scale_id: 23, semitone_cnt: 3, accidental_id: 1, interval_id: 4, tone_type_id: 1 },
  { id: 158, scale_id: 23, semitone_cnt: 4, accidental_id: 1, interval_id: 6, tone_type_id: 3 },
  { id: 159, scale_id: 23, semitone_cnt: 6, accidental_id: 1, interval_id: 9, tone_type_id: 1 },
  { id: 160, scale_id: 23, semitone_cnt: 8, accidental_id: 1, interval_id: 22, tone_type_id: 2 },
  { id: 161, scale_id: 23, semitone_cnt: 9, accidental_id: 2, interval_id: 15, tone_type_id: 1 },
  # メジャーペンタトニックスケール
  { id: 162, scale_id: 24, semitone_cnt: 0, accidental_id: 1, interval_id: 1, tone_type_id: 1 },
  { id: 163, scale_id: 24, semitone_cnt: 2, accidental_id: 1, interval_id: 18, tone_type_id: 2 },
  { id: 164, scale_id: 24, semitone_cnt: 4, accidental_id: 1, interval_id: 5, tone_type_id: 1 },
  { id: 165, scale_id: 24, semitone_cnt: 7, accidental_id: 1, interval_id: 10, tone_type_id: 1 },
  { id: 166, scale_id: 24, semitone_cnt: 9, accidental_id: 1, interval_id: 13, tone_type_id: 1 },
  # メジャーペンタトニックスケール
  { id: 167, scale_id: 25, semitone_cnt: 0, accidental_id: 1, interval_id: 1, tone_type_id: 1 },
  { id: 168, scale_id: 25, semitone_cnt: 3, accidental_id: 1, interval_id: 4, tone_type_id: 1 },
  { id: 169, scale_id: 25, semitone_cnt: 5, accidental_id: 1, interval_id: 20, tone_type_id: 2 },
  { id: 170, scale_id: 25, semitone_cnt: 7, accidental_id: 1, interval_id: 10, tone_type_id: 1 },
  { id: 171, scale_id: 25, semitone_cnt: 10, accidental_id: 1, interval_id: 15, tone_type_id: 1 },
  # メジャーブルーススケール
  { id: 172, scale_id: 26, semitone_cnt: 0, accidental_id: 1, interval_id: 1, tone_type_id: 1 },
  { id: 173, scale_id: 26, semitone_cnt: 2, accidental_id: 1, interval_id: 18, tone_type_id: 2 },
  { id: 174, scale_id: 26, semitone_cnt: 4, accidental_id: 3, interval_id: 4, tone_type_id: 4 },
  { id: 175, scale_id: 26, semitone_cnt: 4, accidental_id: 1, interval_id: 5, tone_type_id: 1 },
  { id: 176, scale_id: 26, semitone_cnt: 7, accidental_id: 1, interval_id: 10, tone_type_id: 1 },
  { id: 177, scale_id: 26, semitone_cnt: 9, accidental_id: 1, interval_id: 13, tone_type_id: 1 },
  # マイナーブルーススケール
  { id: 178, scale_id: 27, semitone_cnt: 0, accidental_id: 1, interval_id: 1, tone_type_id: 1 },
  { id: 179, scale_id: 27, semitone_cnt: 3, accidental_id: 1, interval_id: 4, tone_type_id: 1 },
  { id: 180, scale_id: 27, semitone_cnt: 5, accidental_id: 1, interval_id: 20, tone_type_id: 2 },
  { id: 181, scale_id: 27, semitone_cnt: 7, accidental_id: 3, interval_id: 9, tone_type_id: 4 },
  { id: 182, scale_id: 27, semitone_cnt: 7, accidental_id: 1, interval_id: 10, tone_type_id: 1 },
  { id: 183, scale_id: 27, semitone_cnt: 10, accidental_id: 1, interval_id: 15, tone_type_id: 1 },
  # ホールトーンスケール
  { id: 184, scale_id: 28, semitone_cnt: 0, accidental_id: 1, interval_id: 1, tone_type_id: 1 },
  { id: 185, scale_id: 28, semitone_cnt: 2, accidental_id: 1, interval_id: 18, tone_type_id: 2 },
  { id: 186, scale_id: 28, semitone_cnt: 4, accidental_id: 1, interval_id: 5, tone_type_id: 1 },
  { id: 187, scale_id: 28, semitone_cnt: 6, accidental_id: 1, interval_id: 21, tone_type_id: 2 },
  { id: 188, scale_id: 28, semitone_cnt: 8, accidental_id: 1, interval_id: 22, tone_type_id: 2 },
  { id: 189, scale_id: 28, semitone_cnt: 10, accidental_id: 1, interval_id: 15, tone_type_id: 1 },
  # ディミニッシュスケール
  { id: 190, scale_id: 29, semitone_cnt: 0, accidental_id: 1, interval_id: 1, tone_type_id: 1 },
  { id: 191, scale_id: 29, semitone_cnt: 2, accidental_id: 1, interval_id: 18, tone_type_id: 2 },
  { id: 192, scale_id: 29, semitone_cnt: 3, accidental_id: 1, interval_id: 4, tone_type_id: 1 },
  { id: 193, scale_id: 29, semitone_cnt: 5, accidental_id: 1, interval_id: 20, tone_type_id: 2 },
  { id: 194, scale_id: 29, semitone_cnt: 6, accidental_id: 1, interval_id: 9, tone_type_id: 1 },
  { id: 195, scale_id: 29, semitone_cnt: 8, accidental_id: 1, interval_id: 22, tone_type_id: 2 },
  { id: 196, scale_id: 29, semitone_cnt: 9, accidental_id: 1, interval_id: 14, tone_type_id: 1 },
  { id: 197, scale_id: 29, semitone_cnt: 11, accidental_id: 1, interval_id: 16, tone_type_id: 2 },
  # ドミナントディミニッシュスケール
  { id: 198, scale_id: 30, semitone_cnt: 0, accidental_id: 1, interval_id: 1, tone_type_id: 1 },
  { id: 199, scale_id: 30, semitone_cnt: 1, accidental_id: 1, interval_id: 17, tone_type_id: 2 },
  { id: 200, scale_id: 30, semitone_cnt: 3, accidental_id: 1, interval_id: 19, tone_type_id: 2 },
  { id: 201, scale_id: 30, semitone_cnt: 4, accidental_id: 1, interval_id: 5, tone_type_id: 1 },
  { id: 202, scale_id: 30, semitone_cnt: 6, accidental_id: 1, interval_id: 21, tone_type_id: 2 },
  { id: 203, scale_id: 30, semitone_cnt: 7, accidental_id: 1, interval_id: 10, tone_type_id: 1 },
  { id: 204, scale_id: 30, semitone_cnt: 9, accidental_id: 1, interval_id: 23, tone_type_id: 2 },
  { id: 205, scale_id: 30, semitone_cnt: 10, accidental_id: 1, interval_id: 15, tone_type_id: 1 },
  # オルタードスケール
  { id: 206, scale_id: 31, semitone_cnt: 0, accidental_id: 1, interval_id: 1, tone_type_id: 1 },
  { id: 207, scale_id: 31, semitone_cnt: 1, accidental_id: 1, interval_id: 17, tone_type_id: 2 },
  { id: 208, scale_id: 31, semitone_cnt: 3, accidental_id: 1, interval_id: 19, tone_type_id: 2 },
  { id: 209, scale_id: 31, semitone_cnt: 4, accidental_id: 1, interval_id: 5, tone_type_id: 1 },
  { id: 210, scale_id: 31, semitone_cnt: 6, accidental_id: 1, interval_id: 21, tone_type_id: 2 },
  { id: 211, scale_id: 31, semitone_cnt: 8, accidental_id: 1, interval_id: 22, tone_type_id: 2 },
  { id: 212, scale_id: 31, semitone_cnt: 10, accidental_id: 1, interval_id: 15, tone_type_id: 1 },
  # ビバップドミナントスケール
  { id: 213, scale_id: 32, semitone_cnt: 0, accidental_id: 1, interval_id: 1, tone_type_id: 1 },
  { id: 214, scale_id: 32, semitone_cnt: 2, accidental_id: 1, interval_id: 18, tone_type_id: 2 },
  { id: 215, scale_id: 32, semitone_cnt: 4, accidental_id: 1, interval_id: 5, tone_type_id: 1 },
  { id: 216, scale_id: 32, semitone_cnt: 5, accidental_id: 1, interval_id: 20, tone_type_id: 3 },
  { id: 217, scale_id: 32, semitone_cnt: 7, accidental_id: 1, interval_id: 10, tone_type_id: 1 },
  { id: 218, scale_id: 32, semitone_cnt: 9, accidental_id: 1, interval_id: 23, tone_type_id: 2 },
  { id: 219, scale_id: 32, semitone_cnt: 10, accidental_id: 1, interval_id: 15, tone_type_id: 1 },
  { id: 220, scale_id: 32, semitone_cnt: 11, accidental_id: 1, interval_id: 16, tone_type_id: 5 },
])
